# source the django completions
source ~/.bash_completion.d/django

# on login, always change into the /vagrant directory to save that
# inevitable step
cd %(remote_path)s

# fix annoyingness with running rqinfo on commandline
export PYTHONIOENCODING=utf-8
